#Start with a base image containing java runtime
#FROM openjdk:17-jdk-slim

#Information around who maintaining the image
#MAINTAINER eazybytes.com

#add the application jar to the image
#COPY target/accounts-0.0.1-SNAPSHOT.jar accounts-0.0.1-SNAPSHOT.jar

#execute the application
#ENTRYPOINT ["java", "-jar", "accounts-0.0.1-SNAPSHOT.jar"]

# Generate docker container: docker build . -t abdrahamane01/accounts:s4
